version: '3.9'

services:
  app-db:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres -q -d postgres -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  axum_backend:
    #build: .
    image: axum_postgres_docker:1.0
    env_file: .env
    ports:
      - ${AXUM_SERVER_PORT}
    depends_on:
      app-db:
        condition: service_healthy

volumes:
  db-data: {}
